"""
Curated question bank for the AI Quiz Generator.

Hand-written, factually-checked questions for the domains students most
commonly study (AI, ML, Data Science, Cybersecurity, DSA, Java, C, C++).
When a topic's name/notes match one of these domains, the quiz generator
pulls straight from here instead of falling back to naive keyword-cycling —
which is what caused the repeated "what is deep / what is learning" bug.

Each domain has: mcq, truefalse, fillblank, subjective — each with
10-15 unique, non-overlapping questions.
"""

QUESTION_BANK = {

    # ================================================================ DSA ===
    "dsa": {
        "mcq": [
            {"q": "What is the time complexity of binary search on a sorted array of n elements?",
             "options": ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "answer": "O(log n)"},
            {"q": "Which data structure uses FIFO (First-In-First-Out) order?",
             "options": ["Stack", "Queue", "Tree", "Graph"], "answer": "Queue"},
            {"q": "Which data structure uses LIFO (Last-In-First-Out) order?",
             "options": ["Queue", "Stack", "Heap", "Array"], "answer": "Stack"},
            {"q": "What is the worst-case time complexity of QuickSort?",
             "options": ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], "answer": "O(n^2)"},
            {"q": "Which traversal of a Binary Search Tree visits nodes in sorted order?",
             "options": ["Pre-order", "Post-order", "In-order", "Level-order"], "answer": "In-order"},
            {"q": "What is the time complexity of inserting at the head of a singly linked list?",
             "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "answer": "O(1)"},
            {"q": "Which data structure is used internally to implement recursion?",
             "options": ["Queue", "Stack", "Array", "Hash table"], "answer": "Stack"},
            {"q": "What is the space complexity of merge sort?",
             "options": ["O(1)", "O(log n)", "O(n)", "O(n^2)"], "answer": "O(n)"},
            {"q": "In a min-heap, where is the smallest element always located?",
             "options": ["Last leaf", "Root", "Any leaf", "Middle"], "answer": "Root"},
            {"q": "Which algorithm finds the shortest path in a weighted graph with non-negative edges?",
             "options": ["DFS", "BFS", "Dijkstra's algorithm", "Bubble sort"], "answer": "Dijkstra's algorithm"},
            {"q": "What is the average time complexity of searching in a hash table?",
             "options": ["O(n)", "O(log n)", "O(1)", "O(n^2)"], "answer": "O(1)"},
            {"q": "Which of these sorting algorithms is NOT comparison-based?",
             "options": ["Merge sort", "Quick sort", "Counting sort", "Heap sort"], "answer": "Counting sort"},
            {"q": "What does DFS stand for?",
             "options": ["Data First Search", "Depth First Search", "Direct File Search", "Dynamic Function Search"], "answer": "Depth First Search"},
        ],
        "truefalse": [
            {"q": "A stack follows First-In-First-Out (FIFO) order.", "answer": False},
            {"q": "Binary search only works on a sorted array.", "answer": True},
            {"q": "The time complexity of accessing an array element by index is O(1).", "answer": True},
            {"q": "A queue follows Last-In-First-Out (LIFO) order.", "answer": False},
            {"q": "In a min-heap, the smallest element is always at the root.", "answer": True},
            {"q": "QuickSort has a worst-case time complexity of O(n log n).", "answer": False},
            {"q": "A singly linked list allows O(1) insertion at the head.", "answer": True},
            {"q": "The standard implementation of DFS uses a queue.", "answer": False},
            {"q": "A complete binary tree with n nodes has a height of O(log n).", "answer": True},
            {"q": "Hashing guarantees O(1) lookup time in every possible case.", "answer": False},
            {"q": "Merge sort is a stable sorting algorithm.", "answer": True},
            {"q": "Dijkstra's algorithm works correctly with negative edge weights.", "answer": False},
        ],
        "fillblank": [
            {"q": "The time complexity of binary search is O(_____).", "answer": "log n"},
            {"q": "A _____ follows the Last-In-First-Out principle.", "answer": "stack"},
            {"q": "A _____ follows the First-In-First-Out principle.", "answer": "queue"},
            {"q": "The worst-case time complexity of QuickSort is O(_____).", "answer": "n^2"},
            {"q": "In-order traversal of a BST returns elements in _____ order.", "answer": "sorted"},
            {"q": "The data structure used to implement recursion internally is the call _____.", "answer": "stack"},
            {"q": "_____ sort has a stable, guaranteed O(n log n) time complexity.", "answer": "Merge"},
            {"q": "A _____ is a tree-based structure where each parent's key is smaller (or larger) than its children's.", "answer": "heap"},
            {"q": "_____'s algorithm finds the shortest path in a graph with non-negative weights.", "answer": "Dijkstra"},
            {"q": "The average time complexity of a hash table lookup is O(_____).", "answer": "1"},
            {"q": "A _____ is a non-linear data structure made of nodes connected by edges, often used to represent networks.", "answer": "graph"},
            {"q": "_____ programming solves problems by breaking them into overlapping subproblems and caching results.", "answer": "Dynamic"},
            {"q": "The _____-order traversal of a binary tree visits the root node before its left and right subtrees.", "answer": "pre"},
            {"q": "Big-O notation describes the _____ bound on an algorithm's growth rate as input size increases.", "answer": "upper"},
            {"q": "A _____ algorithm makes the locally optimal choice at each step, hoping it leads to a global optimum.", "answer": "greedy"},
        ],
        "subjective": [
            {"q": "Explain the difference between a stack and a queue with a real-world example.", "answer": "LIFO vs FIFO"},
            {"q": "What is the time and space complexity of merge sort, and why is it considered stable?", "answer": "O(n log n) time, O(n) space"},
            {"q": "Describe how a binary search tree maintains its ordering property.", "answer": "left < node < right"},
            {"q": "Explain how a hash table handles collisions.", "answer": "chaining or open addressing"},
            {"q": "What is the difference between BFS and DFS, and when would you use each?", "answer": "queue vs stack traversal"},
            {"q": "Explain Dijkstra's algorithm and the type of problems it solves.", "answer": "shortest path, non-negative weights"},
            {"q": "What is dynamic programming, and how does it differ from plain recursion?", "answer": "overlapping subproblems, memoization"},
            {"q": "Describe the difference between an array and a linked list in memory and access time.", "answer": "contiguous vs linked, O(1) vs O(n) access"},
            {"q": "What is a heap, and how is it used to implement a priority queue?", "answer": "complete tree, root is min/max"},
            {"q": "Explain Big-O notation and why it matters when analyzing algorithms.", "answer": "upper bound on growth rate"},
            {"q": "What is a greedy algorithm, and how does it differ from dynamic programming?", "answer": "local optimum vs global optimum via subproblems"},
            {"q": "Explain what a graph is and the difference between a directed and an undirected graph.", "answer": "nodes and edges, one-way vs two-way"},
            {"q": "Describe the difference between pre-order, in-order, and post-order tree traversal.", "answer": "order in which the root is visited"},
            {"q": "What is a trie, and what problem is it especially good at solving?", "answer": "prefix-based string search"},
            {"q": "Explain the difference between best-case, average-case, and worst-case time complexity.", "answer": "different input scenarios"},
        ],
    },

    # =============================================================== JAVA ===
    "java": {
        "mcq": [
            {"q": "Which keyword is used to inherit a class in Java?",
             "options": ["implements", "extends", "inherits", "super"], "answer": "extends"},
            {"q": "Which of the following is NOT a primitive data type in Java?",
             "options": ["int", "float", "String", "boolean"], "answer": "String"},
            {"q": "What is the default value of a boolean variable in Java?",
             "options": ["true", "false", "null", "0"], "answer": "false"},
            {"q": "Which method is the entry point of a Java program?",
             "options": ["start()", "run()", "main()", "init()"], "answer": "main()"},
            {"q": "Which keyword prevents a class from being inherited?",
             "options": ["static", "final", "private", "abstract"], "answer": "final"},
            {"q": "What is the size of an int in Java?",
             "options": ["8 bits", "16 bits", "32 bits", "64 bits"], "answer": "32 bits"},
            {"q": "Which collection class does NOT allow duplicate elements?",
             "options": ["ArrayList", "LinkedList", "HashSet", "Vector"], "answer": "HashSet"},
            {"q": "Which construct is used for exception handling in Java?",
             "options": ["try-catch", "if-else", "switch-case", "for-loop"], "answer": "try-catch"},
            {"q": "What does JVM stand for?",
             "options": ["Java Verified Machine", "Java Virtual Machine", "Java Variable Method", "Java Visual Model"], "answer": "Java Virtual Machine"},
            {"q": "Which keyword is used to create an object in Java?",
             "options": ["new", "create", "object", "this"], "answer": "new"},
            {"q": "Which interface has no methods and is used purely to 'mark' a class?",
             "options": ["Runnable", "Serializable", "Comparable", "Iterable"], "answer": "Serializable"},
            {"q": "Which access modifier makes a member accessible only within its own class?",
             "options": ["public", "protected", "private", "default"], "answer": "private"},
        ],
        "truefalse": [
            {"q": "Java supports multiple inheritance through classes.", "answer": False},
            {"q": "In Java, an interface can have both abstract and default methods.", "answer": True},
            {"q": "The 'static' keyword means a member belongs to the class rather than an instance.", "answer": True},
            {"q": "Java uses raw pointers for direct memory manipulation like C++.", "answer": False},
            {"q": "A String object in Java is mutable.", "answer": False},
            {"q": "The 'final' keyword can be applied to variables, methods, and classes.", "answer": True},
            {"q": "Java source code is compiled directly to native machine code with no intermediate form.", "answer": False},
            {"q": "ArrayList is backed internally by a dynamic array.", "answer": True},
            {"q": "In Java, all exceptions must be checked exceptions.", "answer": False},
            {"q": "The 'this' keyword refers to the current object instance.", "answer": True},
            {"q": "Java allows operator overloading like C++.", "answer": False},
            {"q": "Garbage collection in Java automatically frees unused memory.", "answer": True},
        ],
        "fillblank": [
            {"q": "The _____ method is the entry point of every Java application.", "answer": "main"},
            {"q": "Java classes inherit from other classes using the _____ keyword.", "answer": "extends"},
            {"q": "_____ is the process by which the JVM automatically frees unused memory.", "answer": "Garbage collection"},
            {"q": "A class implements multiple _____ in Java to achieve multiple-inheritance-like behavior.", "answer": "interfaces"},
            {"q": "The _____ keyword prevents a variable from being reassigned.", "answer": "final"},
            {"q": "JVM stands for Java _____ Machine.", "answer": "Virtual"},
            {"q": "_____ handling in Java uses try, catch, and finally blocks.", "answer": "Exception"},
            {"q": "A _____ interface in Java has no methods and only marks a class with special behavior.", "answer": "marker"},
            {"q": "The _____ collection class in Java does not allow duplicate elements.", "answer": "HashSet"},
            {"q": "In Java, _____ is the default value of an uninitialized boolean variable.", "answer": "false"},
            {"q": "In Java, the _____ Framework provides classes like ArrayList, HashSet, and HashMap.", "answer": "Collections"},
            {"q": "Method _____ lets a subclass provide a specific implementation of a method already defined in its parent class.", "answer": "overriding"},
            {"q": "Method _____ allows multiple methods with the same name but different parameter lists in one class.", "answer": "overloading"},
            {"q": "Java achieves platform independence because source code compiles to _____ that runs on any JVM.", "answer": "bytecode"},
            {"q": "The _____ block always executes after a try-catch, whether or not an exception occurred.", "answer": "finally"},
        ],
        "subjective": [
            {"q": "Explain the difference between an abstract class and an interface in Java.", "answer": "partial vs full abstraction"},
            {"q": "What is the difference between '==' and '.equals()' when comparing objects?", "answer": "reference vs value equality"},
            {"q": "Describe how exception handling works using try-catch-finally.", "answer": "catch and recover from errors"},
            {"q": "What is the purpose of the 'static' keyword, and how does it differ from instance members?", "answer": "belongs to class, not instance"},
            {"q": "Explain the concept of garbage collection in Java.", "answer": "automatic memory reclamation"},
            {"q": "What is polymorphism, and how is it achieved in Java?", "answer": "overloading and overriding"},
            {"q": "Describe the difference between checked and unchecked exceptions.", "answer": "compile-time vs runtime checked"},
            {"q": "Explain how Java achieves platform independence through the JVM.", "answer": "bytecode runs on any JVM"},
            {"q": "What is the difference between an ArrayList and a LinkedList in Java?", "answer": "array-backed vs node-backed"},
            {"q": "Explain the concept of constructor overloading with an example.", "answer": "multiple constructors, different params"},
            {"q": "What is multithreading in Java, and why might a program use multiple threads?", "answer": "concurrent execution"},
            {"q": "Explain the difference between method overloading and method overriding in Java.", "answer": "same class vs subclass"},
            {"q": "What is the Java Collections Framework, and name two commonly used classes in it.", "answer": "ArrayList, HashMap, etc."},
            {"q": "Describe how Java's platform independence works through the JVM and bytecode.", "answer": "compile once, run anywhere"},
            {"q": "What is the difference between an ArrayList and a plain array in Java?", "answer": "resizable vs fixed size"},
        ],
    },

    # ==================================================================== C ===
    "c": {
        "mcq": [
            {"q": "Which function is commonly used to dynamically allocate a block of memory in C?",
             "options": ["malloc()", "new", "alloc()", "create()"], "answer": "malloc()"},
            {"q": "What is the correct format specifier to print an integer in C?",
             "options": ["%d", "%f", "%s", "%c"], "answer": "%d"},
            {"q": "Which header file declares printf() and scanf()?",
             "options": ["<stdlib.h>", "<stdio.h>", "<string.h>", "<math.h>"], "answer": "<stdio.h>"},
            {"q": "What does the 'sizeof' operator return?",
             "options": ["The value of a variable", "The memory size in bytes of a type/variable", "The address of a variable", "The type of a variable"],
             "answer": "The memory size in bytes of a type/variable"},
            {"q": "Which operator accesses the value stored at the address held by a pointer?",
             "options": ["&", "*", "%", "#"], "answer": "*"},
            {"q": "What is the default return type of a function in C if none is specified (pre-C99)?",
             "options": ["void", "int", "float", "char"], "answer": "int"},
            {"q": "Which of these correctly declares a pointer to an integer?",
             "options": ["int ptr;", "int *ptr;", "pointer int ptr;", "*int ptr;"], "answer": "int *ptr;"},
            {"q": "What is the purpose of the 'free()' function in C?",
             "options": ["Allocate memory", "Deallocate previously allocated memory", "Copy memory", "Compare memory"],
             "answer": "Deallocate previously allocated memory"},
            {"q": "Which loop is guaranteed to execute its body at least once?",
             "options": ["for", "while", "do-while", "if"], "answer": "do-while"},
            {"q": "What is the size of a 'char' data type in C on most systems?",
             "options": ["1 byte", "2 bytes", "4 bytes", "8 bytes"], "answer": "1 byte"},
            {"q": "Which keyword is used to define a constant in C?",
             "options": ["final", "const", "constant", "static"], "answer": "const"},
            {"q": "What does the '&' operator do when placed before a variable name?",
             "options": ["Dereferences a pointer", "Returns the address of the variable", "Performs bitwise AND", "Declares a reference"],
             "answer": "Returns the address of the variable"},
        ],
        "truefalse": [
            {"q": "C is a statically typed language.", "answer": True},
            {"q": "C natively supports object-oriented programming with classes.", "answer": False},
            {"q": "Arrays in C are zero-indexed.", "answer": True},
            {"q": "The 'malloc()' function automatically initializes allocated memory to zero.", "answer": False},
            {"q": "In C, a pointer stores the memory address of another variable.", "answer": True},
            {"q": "C performs automatic garbage collection.", "answer": False},
            {"q": "A 'do-while' loop checks its condition before executing the loop body.", "answer": False},
            {"q": "String literals in C are terminated by a null character '\\0'.", "answer": True},
            {"q": "The '==' operator is used for assignment in C.", "answer": False},
            {"q": "Global variables in C are accessible from any function in the same file by default.", "answer": True},
            {"q": "C supports function overloading like C++.", "answer": False},
            {"q": "The 'sizeof' operator is evaluated at compile time for most built-in types.", "answer": True},
        ],
        "fillblank": [
            {"q": "The _____ function is used to dynamically allocate memory in C.", "answer": "malloc"},
            {"q": "The header file _____ must be included to use printf() and scanf().", "answer": "stdio.h"},
            {"q": "A _____ variable stores the memory address of another variable.", "answer": "pointer"},
            {"q": "The _____ operator returns the memory address of a variable.", "answer": "&"},
            {"q": "The _____ loop is guaranteed to run its body at least once.", "answer": "do-while"},
            {"q": "The _____ function is used to release dynamically allocated memory.", "answer": "free"},
            {"q": "In C, strings are terminated by the _____ character.", "answer": "null"},
            {"q": "The _____ keyword declares a variable whose value cannot be changed.", "answer": "const"},
            {"q": "The _____ operator is used to dereference a pointer.", "answer": "*"},
            {"q": "The size (in bytes) of a variable or type can be found using the _____ operator.", "answer": "sizeof"},
            {"q": "A _____ groups related variables of different data types under a single name in C.", "answer": "struct"},
            {"q": "The _____ preprocessor directive includes the contents of another file, such as a header.", "answer": "#include"},
            {"q": "A variable declared inside a function, accessible only there, is called a _____ variable.", "answer": "local"},
            {"q": "_____ operators (&, |, ^, ~, <<, >>) manipulate individual bits of data.", "answer": "Bitwise"},
            {"q": "A pointer that points to no valid memory location is called a _____ pointer.", "answer": "NULL"},
        ],
        "subjective": [
            {"q": "Explain the difference between 'malloc()' and 'calloc()' in C.", "answer": "calloc zero-initializes"},
            {"q": "What is a pointer, and why is it useful in C programming?", "answer": "stores memory address"},
            {"q": "Describe the difference between call by value and call by reference in C.", "answer": "copy vs address passed"},
            {"q": "Explain the concept of memory leaks and how they occur in C.", "answer": "unfreed allocated memory"},
            {"q": "What is the difference between a structure (struct) and a union in C?", "answer": "separate vs shared memory"},
            {"q": "Explain how arrays and pointers are related in C.", "answer": "array name decays to pointer"},
            {"q": "Describe the purpose of the 'static' keyword inside a function in C.", "answer": "value persists between calls"},
            {"q": "What is recursion? Explain with a simple example like factorial.", "answer": "function calling itself"},
            {"q": "Explain the difference between local and global variables in C.", "answer": "scope and lifetime"},
            {"q": "What are header files, and why are they used in C programs?", "answer": "declarations shared across files"},
            {"q": "What is a segmentation fault, and what commonly causes one in C?", "answer": "invalid memory access"},
            {"q": "Explain the difference between a struct and a function in C.", "answer": "data grouping vs code reuse"},
            {"q": "What are preprocessor directives, and give two examples used in C programs.", "answer": "#include, #define"},
            {"q": "Describe what happens if you forget to call free() after malloc() in C.", "answer": "memory leak"},
            {"q": "Explain the difference between passing an array and passing a single variable to a function in C.", "answer": "address vs copy of value"},
        ],
    },

    # ================================================================== C++ ===
    "cpp": {
        "mcq": [
            {"q": "Which C++ feature allows a function to work with different data types via generic code?",
             "options": ["Inheritance", "Templates", "Encapsulation", "Abstraction"], "answer": "Templates"},
            {"q": "Which keyword is used to define a class in C++?",
             "options": ["struct", "class", "object", "interface"], "answer": "class"},
            {"q": "What is the default access specifier for members of a class in C++?",
             "options": ["public", "protected", "private", "internal"], "answer": "private"},
            {"q": "Which operator is used to allocate memory dynamically in C++?",
             "options": ["malloc", "new", "alloc", "create"], "answer": "new"},
            {"q": "What is a constructor in C++?",
             "options": ["A function that destroys an object", "A special function that initializes an object", "A loop", "A variable"],
             "answer": "A special function that initializes an object"},
            {"q": "Which concept lets a derived class provide its own implementation of a base class method?",
             "options": ["Overloading", "Overriding", "Encapsulation", "Abstraction"], "answer": "Overriding"},
            {"q": "Which C++ feature restricts direct access to an object's internal data?",
             "options": ["Inheritance", "Polymorphism", "Encapsulation", "Overloading"], "answer": "Encapsulation"},
            {"q": "What is the main purpose of a virtual function in C++?",
             "options": ["To make a function faster", "To enable runtime polymorphism", "To prevent overriding", "To allocate memory"],
             "answer": "To enable runtime polymorphism"},
            {"q": "Which operator releases memory allocated with 'new'?",
             "options": ["free", "delete", "remove", "clear"], "answer": "delete"},
            {"q": "What does STL stand for in C++?",
             "options": ["Standard Type Library", "Standard Template Library", "Static Type List", "System Template Language"],
             "answer": "Standard Template Library"},
            {"q": "Which construct is used to handle exceptions in C++?",
             "options": ["try-catch", "if-else", "switch", "goto"], "answer": "try-catch"},
            {"q": "What is multiple inheritance in C++?",
             "options": ["A class inheriting from multiple base classes", "A function with multiple return types", "Multiple objects of a class", "Multiple constructors"],
             "answer": "A class inheriting from multiple base classes"},
        ],
        "truefalse": [
            {"q": "C++ supports both procedural and object-oriented programming.", "answer": True},
            {"q": "A constructor in C++ has the same name as its class.", "answer": True},
            {"q": "C++ does not support operator overloading.", "answer": False},
            {"q": "A virtual function enables runtime (dynamic) polymorphism.", "answer": True},
            {"q": "Private members of a class can be accessed directly from outside the class.", "answer": False},
            {"q": "C++ allows a class to inherit from multiple base classes.", "answer": True},
            {"q": "The 'new' operator in C++ both allocates memory and calls the constructor.", "answer": True},
            {"q": "A destructor in C++ can take arguments.", "answer": False},
            {"q": "Templates in C++ allow writing generic, type-independent code.", "answer": True},
            {"q": "In C++, 'struct' and 'class' differ only in their default access specifier.", "answer": True},
            {"q": "C++ has built-in automatic garbage collection like Java.", "answer": False},
            {"q": "Function overloading allows multiple functions with the same name but different parameters.", "answer": True},
        ],
        "fillblank": [
            {"q": "The _____ operator is used to dynamically allocate memory in C++.", "answer": "new"},
            {"q": "The _____ operator is used to release memory allocated with 'new'.", "answer": "delete"},
            {"q": "A _____ function enables runtime polymorphism in C++.", "answer": "virtual"},
            {"q": "STL stands for Standard _____ Library.", "answer": "Template"},
            {"q": "The default access specifier for a C++ class is _____.", "answer": "private"},
            {"q": "A _____ is a special member function that initializes an object when it's created.", "answer": "constructor"},
            {"q": "_____ inheritance lets a class inherit from more than one base class.", "answer": "Multiple"},
            {"q": "_____ restricts direct access to an object's internal data, exposing it only through methods.", "answer": "Encapsulation"},
            {"q": "A pure _____ function has no implementation in the base class, making that class abstract.", "answer": "virtual"},
            {"q": "The _____ keyword is used to catch exceptions thrown inside a try block.", "answer": "catch"},
            {"q": "A _____ pointer automatically manages the lifetime of a dynamically allocated object, like unique_ptr or shared_ptr.", "answer": "smart"},
            {"q": "A _____ function is not a member of a class but is granted access to its private members.", "answer": "friend"},
            {"q": "_____ overloading lets you redefine how operators like + or == behave for user-defined types.", "answer": "Operator"},
            {"q": "A _____ is an alias for another variable, letting you access it under a different name.", "answer": "reference"},
            {"q": "A _____ groups related names together to avoid naming conflicts in large C++ programs.", "answer": "namespace"},
        ],
        "subjective": [
            {"q": "Explain the four pillars of object-oriented programming as applied in C++.", "answer": "encapsulation, abstraction, inheritance, polymorphism"},
            {"q": "What is the difference between function overloading and function overriding?", "answer": "compile-time vs runtime"},
            {"q": "Describe the difference between a constructor and a destructor.", "answer": "initializes vs cleans up"},
            {"q": "Explain what a virtual function is and how it enables polymorphism.", "answer": "runtime dispatch via vtable"},
            {"q": "What is the difference between 'struct' and 'class' in C++?", "answer": "default access specifier"},
            {"q": "Explain the concept of templates in C++ and why they're useful.", "answer": "generic, type-independent code"},
            {"q": "What is a pure virtual function, and what does it mean for a class to be abstract?", "answer": "no implementation, must override"},
            {"q": "Describe the difference between stack and heap memory allocation in C++.", "answer": "automatic vs manual lifetime"},
            {"q": "Explain how exception handling works in C++ using try, catch, and throw.", "answer": "throw raises, catch handles"},
            {"q": "What is the diamond problem in multiple inheritance, and how does C++ address it?", "answer": "virtual inheritance"},
            {"q": "What is a smart pointer, and why is it preferred over raw pointers in modern C++?", "answer": "automatic memory management"},
            {"q": "Explain the difference between a reference and a pointer in C++.", "answer": "alias vs address, reseatable"},
            {"q": "What is operator overloading, and give an example of when it's useful.", "answer": "custom operator behavior"},
            {"q": "Describe what the Standard Template Library (STL) provides and name two of its components.", "answer": "containers, algorithms, iterators"},
            {"q": "What is the difference between a shallow copy and a deep copy in C++?", "answer": "shared vs duplicated memory"},
        ],
    },

    # =================================================================== AI ===
    "ai": {
        "mcq": [
            {"q": "Who coined the term 'Artificial Intelligence' at the 1956 Dartmouth Conference?",
             "options": ["Alan Turing", "John McCarthy", "Geoffrey Hinton", "Marvin Minsky"], "answer": "John McCarthy"},
            {"q": "What does the Turing Test evaluate?",
             "options": ["A machine's processing speed", "A machine's ability to exhibit human-like intelligent behavior", "A machine's memory capacity", "A machine's power consumption"],
             "answer": "A machine's ability to exhibit human-like intelligent behavior"},
            {"q": "Which search algorithm explores all neighboring nodes before going deeper?",
             "options": ["DFS", "BFS", "A*", "Greedy search"], "answer": "BFS"},
            {"q": "What is the primary goal of a heuristic function in search algorithms like A*?",
             "options": ["To guarantee the shortest path always", "To estimate the cost from the current node to the goal", "To store visited nodes", "To randomize the search"],
             "answer": "To estimate the cost from the current node to the goal"},
            {"q": "Which of these is a classic example of a rule-based, knowledge-based AI system?",
             "options": ["Expert system", "Convolutional neural network", "Random forest", "K-means clustering"], "answer": "Expert system"},
            {"q": "What is Natural Language Processing (NLP) primarily concerned with?",
             "options": ["Robot movement", "Enabling computers to understand and generate human language", "Image recognition", "Circuit design"],
             "answer": "Enabling computers to understand and generate human language"},
            {"q": "Which best describes 'supervised learning'?",
             "options": ["Learning from labeled input-output pairs", "Learning without any data", "Learning only from rewards", "Clustering unlabeled data"],
             "answer": "Learning from labeled input-output pairs"},
            {"q": "In AI, what is an 'agent'?",
             "options": ["A type of database", "An entity that perceives its environment and acts upon it", "A programming language", "A neural network layer"],
             "answer": "An entity that perceives its environment and acts upon it"},
            {"q": "What is the main idea behind reinforcement learning?",
             "options": ["Learning from labeled examples", "Learning by trial and error using rewards and penalties", "Memorizing a dataset", "Clustering similar data points"],
             "answer": "Learning by trial and error using rewards and penalties"},
            {"q": "Which of these is a classic AI planning/search problem?",
             "options": ["Sorting an array", "The Towers of Hanoi", "Printing 'Hello World'", "Reading a file"], "answer": "The Towers of Hanoi"},
            {"q": "What does 'AGI' stand for?",
             "options": ["Automated General Interface", "Artificial General Intelligence", "Applied Graph Inference", "Advanced Gradient Iteration"],
             "answer": "Artificial General Intelligence"},
            {"q": "Which technique is classically used in game-playing AI (like chess) to choose the best move?",
             "options": ["Linear regression", "Minimax algorithm", "K-means clustering", "Principal Component Analysis"], "answer": "Minimax algorithm"},
        ],
        "truefalse": [
            {"q": "The Turing Test was proposed by Alan Turing.", "answer": True},
            {"q": "All AI systems are based on neural networks.", "answer": False},
            {"q": "An expert system uses a knowledge base and inference rules to make decisions.", "answer": True},
            {"q": "Reinforcement learning requires a labeled example for every possible action.", "answer": False},
            {"q": "The term 'Artificial Intelligence' was coined at the 1956 Dartmouth Conference.", "answer": True},
            {"q": "A* search uses a heuristic to guide its search more efficiently toward the goal.", "answer": True},
            {"q": "Narrow AI is designed for a specific task, unlike Artificial General Intelligence.", "answer": True},
            {"q": "Natural Language Processing deals exclusively with speech recognition.", "answer": False},
            {"q": "Breadth-First Search always finds the shortest path in an unweighted graph.", "answer": True},
            {"q": "In Minimax, one player maximizes the score while the opponent minimizes it.", "answer": True},
            {"q": "An AI agent's 'environment' can only refer to a physical, robotic environment.", "answer": False},
            {"q": "Symbolic AI relies on explicit rules and logic rather than learning from data.", "answer": True},
        ],
        "fillblank": [
            {"q": "The term 'Artificial Intelligence' was coined by _____ in 1956.", "answer": "John McCarthy"},
            {"q": "The _____ Test evaluates whether a machine's behavior is indistinguishable from a human's.", "answer": "Turing"},
            {"q": "_____ systems use a knowledge base and inference engine to mimic expert decision-making.", "answer": "Expert"},
            {"q": "In search algorithms, a _____ function estimates the cost from a node to the goal.", "answer": "heuristic"},
            {"q": "_____ learning trains an agent through rewards and penalties rather than labeled data.", "answer": "Reinforcement"},
            {"q": "NLP stands for Natural _____ Processing.", "answer": "Language"},
            {"q": "The _____ algorithm is used in two-player games to choose moves by minimizing the opponent's best outcome.", "answer": "Minimax"},
            {"q": "An AI _____ perceives its environment through sensors and acts through actuators.", "answer": "agent"},
            {"q": "_____ AI refers to systems designed for one specific task, as opposed to general intelligence.", "answer": "Narrow"},
            {"q": "A* is an example of an _____ search algorithm, since it uses extra knowledge to guide the search.", "answer": "informed"},
            {"q": "A _____ system encodes human expert knowledge as explicit rules to make decisions in a specific domain.", "answer": "expert"},
            {"q": "The Towers of _____ is a classic AI planning problem involving moving disks between three pegs.", "answer": "Hanoi"},
            {"q": "AGI stands for Artificial _____ Intelligence.", "answer": "General"},
            {"q": "A rule-based approach that relies on explicit logic rather than learning from data is known as _____ AI.", "answer": "symbolic"},
            {"q": "In Minimax, one player tries to _____ the score while the opponent tries to minimize it.", "answer": "maximize"},
        ],
        "subjective": [
            {"q": "Explain the difference between Narrow AI and Artificial General Intelligence (AGI).", "answer": "task-specific vs general"},
            {"q": "What is the Turing Test, and what are its criticisms?", "answer": "imitation game"},
            {"q": "Describe the difference between informed search (A*) and uninformed search (BFS).", "answer": "heuristic vs blind search"},
            {"q": "What is an expert system, and how does it differ from a modern ML model?", "answer": "rules vs learned patterns"},
            {"q": "Explain the concept of an 'agent' and its 'environment' in AI.", "answer": "perceive and act"},
            {"q": "What is the difference between reinforcement learning and supervised learning?", "answer": "rewards vs labels"},
            {"q": "Describe how the Minimax algorithm works in game-playing AI.", "answer": "maximize vs minimize"},
            {"q": "What are some real-world applications of Natural Language Processing?", "answer": "translation, chatbots, search"},
            {"q": "Explain the difference between symbolic AI and data-driven AI.", "answer": "rules vs statistics"},
            {"q": "What ethical concerns are commonly raised about artificial intelligence?", "answer": "bias, privacy, job displacement"},
            {"q": "What is a heuristic function, and why is it useful in search algorithms like A*?", "answer": "estimates cost to goal"},
            {"q": "Describe what AGI means and how it differs from the AI systems in use today.", "answer": "human-level general reasoning"},
            {"q": "Explain how an expert system makes decisions, using an example domain like medical diagnosis.", "answer": "knowledge base plus inference rules"},
            {"q": "What is the Towers of Hanoi problem, and what does it demonstrate about problem-solving in AI?", "answer": "recursive planning puzzle"},
            {"q": "Explain the difference between a search problem's state space and its goal state, using a simple example.", "answer": "all configurations vs the target one"},
        ],
    },

    # =================================================== ML / DEEP LEARNING ===
    "ml": {
        "mcq": [
            {"q": "What is 'overfitting' in machine learning?",
             "options": ["When a model performs well on both training and test data", "When a model learns the training data too well, including noise, and performs poorly on new data", "When a model has too few parameters", "When training takes too long"],
             "answer": "When a model learns the training data too well, including noise, and performs poorly on new data"},
            {"q": "Which of these is a supervised learning algorithm?",
             "options": ["K-means clustering", "Linear regression", "Principal Component Analysis", "Apriori algorithm"], "answer": "Linear regression"},
            {"q": "What is the purpose of a loss function?",
             "options": ["To visualize data", "To measure how far predictions are from actual values", "To store the dataset", "To split data into train/test sets"],
             "answer": "To measure how far predictions are from actual values"},
            {"q": "Which technique randomly disables neurons during training to reduce overfitting?",
             "options": ["Batch normalization", "Dropout", "Padding", "Pooling"], "answer": "Dropout"},
            {"q": "What does 'gradient descent' do?",
             "options": ["Splits data into batches", "Iteratively adjusts model parameters to minimize the loss function", "Removes outliers", "Encodes categorical variables"],
             "answer": "Iteratively adjusts model parameters to minimize the loss function"},
            {"q": "In a Convolutional Neural Network (CNN), what does a convolutional layer primarily do?",
             "options": ["Classify text", "Extract spatial features like edges and shapes from images", "Store training data", "Normalize labels"],
             "answer": "Extract spatial features like edges and shapes from images"},
            {"q": "What is k-fold cross-validation used for?",
             "options": ["Increasing dataset size", "Evaluating model performance more reliably across different data splits", "Reducing the number of features", "Visualizing decision boundaries"],
             "answer": "Evaluating model performance more reliably across different data splits"},
            {"q": "Which best describes 'unsupervised learning'?",
             "options": ["Learning from labeled data", "Finding patterns or structure in data without labeled outputs", "Learning purely from rewards", "Predicting only continuous values"],
             "answer": "Finding patterns or structure in data without labeled outputs"},
            {"q": "The vanishing gradient problem is most commonly associated with which of these?",
             "options": ["Decision trees", "Deep neural networks with many layers", "K-means clustering", "Linear regression"], "answer": "Deep neural networks with many layers"},
            {"q": "Which activation function outputs values between 0 and 1, often used for binary classification?",
             "options": ["ReLU", "Sigmoid", "Tanh", "Softmax"], "answer": "Sigmoid"},
            {"q": "What distinguishes a Recurrent Neural Network (RNN) from a standard feedforward network?",
             "options": ["RNNs have no layers", "RNNs have loops that let information persist across time steps", "RNNs cannot be trained", "RNNs only work on images"],
             "answer": "RNNs have loops that let information persist across time steps"},
            {"q": "What does 'backpropagation' do when training a neural network?",
             "options": ["Collects new data", "Computes gradients of the loss with respect to weights by propagating error backward", "Randomly initializes weights", "Splits the dataset"],
             "answer": "Computes gradients of the loss with respect to weights by propagating error backward"},
        ],
        "truefalse": [
            {"q": "Overfitting means a model performs poorly on training data but well on unseen data.", "answer": False},
            {"q": "Linear regression is a supervised learning algorithm.", "answer": True},
            {"q": "Deep learning is a subset of machine learning that uses neural networks with multiple layers.", "answer": True},
            {"q": "Dropout is a regularization technique used to reduce overfitting in neural networks.", "answer": True},
            {"q": "K-means is a supervised classification algorithm.", "answer": False},
            {"q": "Gradient descent is used to minimize the loss function during training.", "answer": True},
            {"q": "A Convolutional Neural Network is primarily designed for sequential text data rather than images.", "answer": False},
            {"q": "Backpropagation calculates gradients by propagating error backward through the network.", "answer": True},
            {"q": "More training data always guarantees a better model regardless of its quality.", "answer": False},
            {"q": "The ReLU activation function outputs zero for all negative inputs.", "answer": True},
            {"q": "Cross-validation helps estimate how well a model generalizes to unseen data.", "answer": True},
            {"q": "Unsupervised learning requires labeled data to find patterns.", "answer": False},
        ],
        "fillblank": [
            {"q": "_____ occurs when a model learns the training data too well, including noise, and fails to generalize.", "answer": "Overfitting"},
            {"q": "The _____ function measures how far a model's predictions are from the actual values.", "answer": "loss"},
            {"q": "_____ is a regularization technique that randomly disables neurons during training.", "answer": "Dropout"},
            {"q": "_____ descent is the optimization algorithm that iteratively minimizes the loss function.", "answer": "Gradient"},
            {"q": "In a CNN, the _____ layer extracts spatial features like edges and textures from images.", "answer": "convolutional"},
            {"q": "_____ learning uses neural networks with many layers to learn complex patterns.", "answer": "Deep"},
            {"q": "_____ computes gradients by propagating error backward through a neural network.", "answer": "Backpropagation"},
            {"q": "K-means is an example of an _____ learning algorithm.", "answer": "unsupervised"},
            {"q": "The _____ activation function outputs a value between 0 and 1.", "answer": "sigmoid"},
            {"q": "_____-fold cross-validation splits data into multiple folds to reliably evaluate a model.", "answer": "K"},
            {"q": "_____ learning is a technique where a pretrained model's knowledge is reused for a new, related task.", "answer": "Transfer"},
            {"q": "The bias-_____ tradeoff describes the balance between a model being too simple and too sensitive to training data.", "answer": "variance"},
            {"q": "_____ networks use loops to let information persist across time steps, making them suited for sequential data.", "answer": "Recurrent"},
            {"q": "An _____ function like ReLU or sigmoid introduces non-linearity into a neural network.", "answer": "activation"},
            {"q": "One complete pass through the entire training dataset during model training is called an _____.", "answer": "epoch"},
        ],
        "subjective": [
            {"q": "Explain the difference between overfitting and underfitting, and how to address each.", "answer": "too complex vs too simple"},
            {"q": "What is the difference between supervised, unsupervised, and reinforcement learning?", "answer": "labels, patterns, rewards"},
            {"q": "Describe how gradient descent works to train a machine learning model.", "answer": "iteratively minimize loss"},
            {"q": "What is a Convolutional Neural Network, and why is it well-suited for image data?", "answer": "spatial feature extraction"},
            {"q": "Explain what backpropagation does and why it's essential for training neural networks.", "answer": "computes gradients backward"},
            {"q": "What is the vanishing gradient problem, and how do techniques like ReLU help?", "answer": "gradients shrink in deep nets"},
            {"q": "Describe the bias-variance tradeoff in machine learning.", "answer": "underfitting vs overfitting balance"},
            {"q": "What is the difference between a Recurrent Neural Network and a Transformer?", "answer": "sequential vs attention-based"},
            {"q": "Explain why cross-validation is used instead of a single train/test split.", "answer": "more reliable performance estimate"},
            {"q": "What is transfer learning, and why is it useful in deep learning?", "answer": "reuse pretrained model knowledge"},
            {"q": "What is an activation function, and why do neural networks need non-linear ones?", "answer": "introduces non-linearity"},
            {"q": "Explain what an epoch is during model training, and how it differs from a batch.", "answer": "full pass vs subset"},
            {"q": "What distinguishes a Recurrent Neural Network's structure from a standard feedforward network?", "answer": "loops carry information across time"},
            {"q": "Describe what a hyperparameter is and give two examples used when training a neural network.", "answer": "learning rate, batch size"},
            {"q": "Why is normalizing or scaling input features often important before training a machine learning model?", "answer": "equal contribution, faster convergence"},
        ],
    },

    # ======================================================= DATA SCIENCE ===
    "data_science": {
        "mcq": [
            {"q": "What is the primary purpose of Exploratory Data Analysis (EDA)?",
             "options": ["To deploy a model to production", "To understand data patterns, distributions, and relationships before modeling", "To write final reports only", "To collect raw data"],
             "answer": "To understand data patterns, distributions, and relationships before modeling"},
            {"q": "Which of these is a common measure of central tendency?",
             "options": ["Standard deviation", "Mean", "Variance", "Range"], "answer": "Mean"},
            {"q": "What does a p-value in hypothesis testing indicate?",
             "options": ["The probability the null hypothesis is true", "The probability of observing results at least this extreme, assuming the null hypothesis is true", "The sample size", "The confidence interval width"],
             "answer": "The probability of observing results at least this extreme, assuming the null hypothesis is true"},
            {"q": "Which Python library is most commonly used for tabular data manipulation (DataFrames)?",
             "options": ["NumPy", "Pandas", "Matplotlib", "Scikit-learn"], "answer": "Pandas"},
            {"q": "What is 'data normalization' typically used for?",
             "options": ["Removing all outliers", "Scaling numeric features to a common range to improve model performance", "Encrypting sensitive data", "Increasing dataset size"],
             "answer": "Scaling numeric features to a common range to improve model performance"},
            {"q": "Which chart best shows the distribution of a single numeric variable?",
             "options": ["Pie chart", "Histogram", "Bar chart of categories", "Scatter plot of two variables"], "answer": "Histogram"},
            {"q": "What does 'correlation' measure between two variables?",
             "options": ["Causation between them", "The strength and direction of their linear relationship", "Their individual variances", "Their sample size"],
             "answer": "The strength and direction of their linear relationship"},
            {"q": "Which is a common technique for handling missing data?",
             "options": ["Ignoring the entire dataset", "Imputation, e.g. filling with mean/median", "Always deleting the whole column", "Duplicating existing rows"],
             "answer": "Imputation, e.g. filling with mean/median"},
            {"q": "What does 'ETL' stand for in data engineering?",
             "options": ["Extract, Transform, Load", "Evaluate, Test, Launch", "Export, Transfer, Log", "Encode, Transmit, Link"], "answer": "Extract, Transform, Load"},
            {"q": "Which statistical concept describes the spread of data around the mean?",
             "options": ["Median", "Mode", "Standard deviation", "Correlation"], "answer": "Standard deviation"},
            {"q": "What is the purpose of a confusion matrix in classification problems?",
             "options": ["To visualize feature correlations", "To summarize predictions against actual labels (true/false positives/negatives)", "To normalize data", "To reduce dimensionality"],
             "answer": "To summarize predictions against actual labels (true/false positives/negatives)"},
            {"q": "Which technique reduces the number of features while preserving as much variance as possible?",
             "options": ["One-hot encoding", "Principal Component Analysis (PCA)", "Min-max scaling", "Label encoding"], "answer": "Principal Component Analysis (PCA)"},
        ],
        "truefalse": [
            {"q": "Correlation between two variables always implies causation.", "answer": False},
            {"q": "Pandas is a Python library commonly used for data manipulation and analysis.", "answer": True},
            {"q": "A p-value below the significance threshold (e.g. 0.05) typically leads to rejecting the null hypothesis.", "answer": True},
            {"q": "Exploratory Data Analysis is normally done after building the final model, not before.", "answer": False},
            {"q": "Standard deviation measures how spread out data points are from the mean.", "answer": True},
            {"q": "A histogram is used to show the relationship between two categorical variables.", "answer": False},
            {"q": "Missing data can sometimes be handled using imputation techniques like mean or median filling.", "answer": True},
            {"q": "PCA is primarily used to increase the number of features in a dataset.", "answer": False},
            {"q": "A confusion matrix is used to evaluate classification model performance.", "answer": True},
            {"q": "ETL stands for Extract, Transform, Load.", "answer": True},
            {"q": "The mean is always a better measure of central tendency than the median, regardless of distribution.", "answer": False},
            {"q": "Data normalization scales numeric features to a common range.", "answer": True},
        ],
        "fillblank": [
            {"q": "_____ is the process of understanding data patterns and relationships before formal modeling.", "answer": "Exploratory Data Analysis"},
            {"q": "The Python library _____ is widely used for working with tabular DataFrames.", "answer": "Pandas"},
            {"q": "A _____ measures the strength and direction of a linear relationship between two variables.", "answer": "correlation"},
            {"q": "_____ is a dimensionality-reduction technique that preserves as much variance as possible.", "answer": "PCA"},
            {"q": "ETL stands for Extract, _____, Load.", "answer": "Transform"},
            {"q": "A _____ visualizes the distribution of a single numeric variable.", "answer": "histogram"},
            {"q": "_____ describes how spread out data points are around the mean.", "answer": "Standard deviation"},
            {"q": "A _____ matrix summarizes a classification model's predictions against actual outcomes.", "answer": "confusion"},
            {"q": "_____ is a common technique for filling missing values using statistics like the mean or median.", "answer": "Imputation"},
            {"q": "A p-value below the significance level typically leads to _____ the null hypothesis.", "answer": "rejecting"},
            {"q": "_____ testing compares two versions of something, like a webpage, to see which performs better.", "answer": "A/B"},
            {"q": "A train-test _____ divides a dataset into a portion for training a model and a portion for evaluating it.", "answer": "split"},
            {"q": "_____-validation splits data into multiple folds to get a more reliable estimate of model performance.", "answer": "Cross"},
            {"q": "An _____ is a data point that differs significantly from the rest of the observations.", "answer": "outlier"},
            {"q": "_____ data refers to extremely large, complex datasets that traditional tools struggle to process.", "answer": "Big"},
        ],
        "subjective": [
            {"q": "What is Exploratory Data Analysis, and why is it an important first step in a project?", "answer": "understand data before modeling"},
            {"q": "Explain the difference between correlation and causation with an example.", "answer": "association vs cause"},
            {"q": "What is a p-value, and how is it used in hypothesis testing?", "answer": "probability under null hypothesis"},
            {"q": "Describe common techniques for handling missing data in a dataset.", "answer": "imputation, deletion"},
            {"q": "What is the difference between mean, median, and mode, and when would you prefer one?", "answer": "average, middle, most frequent"},
            {"q": "Explain what a confusion matrix tells you about a classification model.", "answer": "true/false positives and negatives"},
            {"q": "What is Principal Component Analysis (PCA), and why might you use it?", "answer": "reduce dimensions, keep variance"},
            {"q": "Describe the ETL process and its role in a data pipeline.", "answer": "extract, transform, load"},
            {"q": "What is the difference between structured and unstructured data?", "answer": "tabular vs free-form"},
            {"q": "Explain why normalization or standardization matters before training some ML models.", "answer": "equal feature scale"},
            {"q": "What is A/B testing, and how is it used to make data-driven decisions?", "answer": "compare two variants"},
            {"q": "Explain the purpose of a train-test split, and why testing on training data alone is misleading.", "answer": "evaluate generalization"},
            {"q": "What is an outlier, and how might it affect a statistical analysis if left untreated?", "answer": "skews mean, distorts model"},
            {"q": "Describe the difference between classification and regression tasks in data science.", "answer": "category vs continuous value"},
            {"q": "What is feature engineering, and why does it matter for model performance?", "answer": "crafting better input variables"},
        ],
    },

    # ===================================================== CYBERSECURITY ===
    "cybersecurity": {
        "mcq": [
            {"q": "What does 'phishing' refer to in cybersecurity?",
             "options": ["A type of firewall", "A social engineering attack that tricks users into revealing sensitive information", "A type of encryption", "A network protocol"],
             "answer": "A social engineering attack that tricks users into revealing sensitive information"},
            {"q": "What is the purpose of a firewall?",
             "options": ["To speed up internet connections", "To monitor and control network traffic based on security rules", "To store passwords", "To compress files"],
             "answer": "To monitor and control network traffic based on security rules"},
            {"q": "What does 'encryption' do to data?",
             "options": ["Deletes it permanently", "Converts it into a coded form to prevent unauthorized access", "Compresses it for storage", "Backs it up automatically"],
             "answer": "Converts it into a coded form to prevent unauthorized access"},
            {"q": "What is a 'DDoS' attack?",
             "options": ["A type of encryption algorithm", "An attack that overwhelms a system with traffic from multiple sources", "A password-cracking technique", "A type of firewall"],
             "answer": "An attack that overwhelms a system with traffic from multiple sources"},
            {"q": "What does two-factor authentication (2FA) add to a login process?",
             "options": ["A second password only", "An additional verification step beyond just a password", "A faster login process", "A backup email"],
             "answer": "An additional verification step beyond just a password"},
            {"q": "What is 'malware'?",
             "options": ["A type of hardware", "Malicious software designed to harm or gain unauthorized access to systems", "A network cable", "A firewall setting"],
             "answer": "Malicious software designed to harm or gain unauthorized access to systems"},
            {"q": "What is the primary purpose of a VPN?",
             "options": ["To increase internet speed", "To create a secure, encrypted connection over a public network", "To block all websites", "To store files in the cloud"],
             "answer": "To create a secure, encrypted connection over a public network"},
            {"q": "What is 'SQL injection'?",
             "options": ["A database backup method", "An attack that inserts malicious SQL code into input fields to manipulate a database", "A type of encryption", "A network configuration"],
             "answer": "An attack that inserts malicious SQL code into input fields to manipulate a database"},
            {"q": "What does the 'CIA triad' stand for in cybersecurity?",
             "options": ["Central Intelligence Agency", "Confidentiality, Integrity, Availability", "Cyber Intelligence Analysis", "Computer Information Access"],
             "answer": "Confidentiality, Integrity, Availability"},
            {"q": "What is a 'zero-day vulnerability'?",
             "options": ["A vulnerability that has existed for zero days", "A software flaw unknown to the vendor and unpatched", "A vulnerability found on day zero of testing", "An outdated antivirus signature"],
             "answer": "A software flaw unknown to the vendor and unpatched"},
            {"q": "What is 'ransomware'?",
             "options": ["Software that speeds up computers", "Malware that encrypts a victim's files and demands payment to decrypt them", "A type of firewall", "An email filtering tool"],
             "answer": "Malware that encrypts a victim's files and demands payment to decrypt them"},
            {"q": "What is the purpose of penetration testing?",
             "options": ["To slow down a network intentionally", "To simulate cyberattacks to find vulnerabilities before attackers do", "To install antivirus software", "To back up data"],
             "answer": "To simulate cyberattacks to find vulnerabilities before attackers do"},
        ],
        "truefalse": [
            {"q": "Phishing attacks rely on tricking users rather than exploiting software vulnerabilities directly.", "answer": True},
            {"q": "A firewall guarantees complete protection against all cyberattacks.", "answer": False},
            {"q": "Encryption converts readable data into an unreadable format to protect it.", "answer": True},
            {"q": "Two-factor authentication uses only a username and password.", "answer": False},
            {"q": "A DDoS attack typically originates from a single source only.", "answer": False},
            {"q": "SQL injection exploits occur through poorly sanitized user input fields.", "answer": True},
            {"q": "The CIA triad stands for Confidentiality, Integrity, and Availability.", "answer": True},
            {"q": "A zero-day vulnerability is one that has already been patched by the vendor.", "answer": False},
            {"q": "Ransomware encrypts a victim's data and demands payment for its release.", "answer": True},
            {"q": "A VPN hides and encrypts a user's internet traffic over public networks.", "answer": True},
            {"q": "Penetration testing is performed by attackers with malicious intent.", "answer": False},
            {"q": "Strong passwords alone are sufficient to guarantee complete account security.", "answer": False},
        ],
        "fillblank": [
            {"q": "_____ is a social engineering attack that tricks users into revealing sensitive information.", "answer": "Phishing"},
            {"q": "A _____ monitors and controls network traffic based on security rules.", "answer": "firewall"},
            {"q": "_____ converts data into a coded form so only authorized parties can read it.", "answer": "Encryption"},
            {"q": "A _____ attack overwhelms a system with traffic from many sources to disrupt service.", "answer": "DDoS"},
            {"q": "_____ authentication adds an extra verification step beyond just a password.", "answer": "Two-factor"},
            {"q": "_____ is malicious software designed to damage or gain unauthorized access to a system.", "answer": "Malware"},
            {"q": "A _____ creates a secure, encrypted connection over a public network.", "answer": "VPN"},
            {"q": "_____ injection attacks insert malicious code into a database query through unsanitized input.", "answer": "SQL"},
            {"q": "The CIA triad stands for Confidentiality, Integrity, and _____.", "answer": "Availability"},
            {"q": "A _____ vulnerability is an unpatched flaw unknown to the software vendor.", "answer": "zero-day"},
            {"q": "_____ is a one-way process that converts data into a fixed-length string, often used to store passwords securely.", "answer": "Hashing"},
            {"q": "A _____ force attack tries many password combinations systematically until the correct one is found.", "answer": "brute"},
            {"q": "In a _____ attack, the attacker secretly intercepts and relays communication between two parties.", "answer": "man-in-the-middle"},
            {"q": "_____ testing simulates real attacks, with permission, to find security weaknesses before real attackers do.", "answer": "Penetration"},
            {"q": "An Intrusion Detection System (IDS) monitors network or system activity for _____ actions.", "answer": "malicious"},
        ],
        "subjective": [
            {"q": "Explain what phishing is and describe common ways to recognize a phishing attempt.", "answer": "fake urgency, spoofed sender"},
            {"q": "What is the CIA triad, and why is each component important?", "answer": "confidentiality, integrity, availability"},
            {"q": "Describe how a firewall works and what it can and cannot protect against.", "answer": "filters traffic by rules"},
            {"q": "What is the difference between a virus, a worm, and ransomware?", "answer": "spread method and payload"},
            {"q": "Explain how SQL injection attacks work and how developers can prevent them.", "answer": "parameterized queries"},
            {"q": "What is two-factor authentication, and why is it more secure than a password alone?", "answer": "something you know + have"},
            {"q": "Describe the purpose and process of penetration testing.", "answer": "authorized simulated attack"},
            {"q": "What is a zero-day vulnerability, and why is it particularly dangerous?", "answer": "unknown, unpatched flaw"},
            {"q": "Explain how a VPN protects a user's data on public networks.", "answer": "encrypted tunnel"},
            {"q": "What steps can an organization take to reduce the risk of a ransomware attack?", "answer": "backups, patching, training"},
            {"q": "What is hashing, and why is it used to store passwords instead of storing them in plain text?", "answer": "one-way, irreversible"},
            {"q": "Explain what a brute force attack is and one common defense against it.", "answer": "try all combinations; lockouts/rate limiting"},
            {"q": "What is a man-in-the-middle attack, and how can encryption help prevent it?", "answer": "intercepted communication"},
            {"q": "Describe the difference between a vulnerability, a threat, and a risk in cybersecurity.", "answer": "flaw vs danger vs likelihood and impact"},
            {"q": "What is social engineering, and why is it often considered the weakest link in security?", "answer": "exploits human trust, not systems"},
        ],
    },
}


DOMAIN_LABELS = {
    "dsa": "Data Structures & Algorithms",
    "java": "Java",
    "c": "C",
    "cpp": "C++",
    "ai": "Artificial Intelligence",
    "ml": "Machine Learning / Deep Learning",
    "data_science": "Data Science",
    "cybersecurity": "Cybersecurity",
}
